version: '3.7'
services:

  usernameapi:
    build:
      context: ${USERNAMEAPI_SRC_DIR}
      dockerfile: Dockerfile
    expose:
      - 3001
    environment: 
      - PG_STRING=${CONNECTION_STRING}
      - VIRTUAL_HOST=${SERVICE_DOMAIN}
      - LETSENCRYPT_HOST=${SERVICE_DOMAIN}
      - VIRTUAL_PORT=3001
      - PORT=3001
    networks:
      - back
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge